version: "3.8"

services:
  backend:
    image: starkadvisor-backend:latest
    container_name: starkadvisor-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - .:/app  # 👈 Esto sincroniza tu código local con /app en el contenedor

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    restart: unless-stopped
