name: Deploy Django Backend (OIDC, no publish profile)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Requerido para OIDC
permissions:
  id-token: write
  contents: read

env:
  PYTHON_VERSION: "3.11"
  APP_NAME: "starkadvisor-backend"   # <-- nombre exacto de tu App Service

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # (Opcional) Validar requirements para fallar aquí si algo de pip está roto
      - name: Install dependencies (validation only)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 🔐 Login con OIDC (sin Publish Profile)
      # Necesitas en GitHub estos secrets (Deployment Center suele crearlos):
      #   AZURE_CLIENT_ID, AZURE_TENANT_ID, AZURE_SUBSCRIPTION_ID
      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 🚀 Deploy al App Service. Sin "package": Oryx construye en Azure usando tus App Settings
      - name: Deploy to Azure Web App (Oryx source-based)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
          # slot-name: production     # (opcional) si usas slots
          # package:                  # dejar vacío para source-based
