name: Deploy Django Backend to Azure App Service (Publish Profile)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # (opcional) Validar requirements para fallar aquí si algo está mal en pip
      - name: Install dependencies (validation only)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 🚀 Deploy sin login explícito (usa Publish Profile)
      # 👉 No pasamos "package" para que Oryx construya en Azure con tus App Settings
      - name: Deploy to Azure Web App (Oryx source-based)
        uses: azure/webapps-deploy@v2
        with:
          app-name: starkadvisor-backend              # ← nombre EXACTO de tu App Service
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          # package:                                   # déjalo vacío (source-based)
