name: Deploy Django Backend to Azure (SP login, Oryx)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # (Opcional) Validación temprana de requirements para fallar aquí si hay algo roto
      - name: Install dependencies (validation only)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 🔐 Login a Azure con Service Principal (evita 'No credentials found')
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 🚀 Despliegue al App Service. Sin 'package' => Oryx construye en Azure con tus App Settings
      - name: Deploy to Azure Web App (source-based)
        uses: azure/webapps-deploy@v2
        with:
          app-name: starkadvisor-backend   # <--- NOMBRE EXACTO de tu App Service
          # slot-name: production          # (opcional) si usas deployment slots
          # package:                       # intencionalmente vacío
