name: Deploy Django Backend to Azure App Service

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Esto valida que requirements.txt instala bien (para fallar temprano si hay error de pip)
      - name: Install dependencies (validation only)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 👉 Oryx hará el build en Azure; NO enviamos zip/artefacto.
      - name: Deploy to Azure Web App (Oryx source-based)
        uses: azure/webapps-deploy@v2
        with:
          app-name: <APP_SERVICE_NAME>            # ej: starkadvisor-backend-f0ekbqfpd6hnf0e6
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          # package: (intencionalmente vacío)
