name: Deploy Django Backend to Azure App Service

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Validación temprana de requirements (para fallar aquí si algo está mal en pip)
      - name: Install dependencies (validation only)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 👉 NO enviamos un zip. Oryx compila en Azure con tus App Settings.
      - name: Deploy to Azure Web App (Oryx source-based)
        uses: azure/webapps-deploy@v2
        with:
          app-name: starkadvisor-backend-f0ekbqfpd6hnf0e6   # <-- Pon aquí el NOMBRE EXACTO de tu App Service
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          # package:  # Intencionalmente vacío para usar Oryx
